// frontend/src/lib/components/AddItemForm.svelte
<script lang="ts">
	import type { Category, ItemPayload } from '$lib/types';
    import * as api from '$lib/api';

	let { categories = [], onAddItem, onAddCategory } = $props<{
        categories: Category[];
        onAddItem: (payload: ItemPayload) => Promise<void>; // Make it async to await
        onAddCategory: (name: string) => Promise<Category>; // Expects the new category back
    }>();

	let itemName = $state('');
	let itemNote = $state('');
	let selectedCategoryId = $state<number | string>(''); // Can be number or 'new'
	let newCategoryName = $state('');
    let priceMatch = $state(false);
	let isSubmitting = $state(false);
	let error = $state<string | null>(null);

    // Set default category if available
    $effect(() => {
        if (categories.length > 0 && $selectedCategoryId === '') {
            $selectedCategoryId = categories[0].id;
        }
    });

	async function handleSubmit() {
		if (!itemName.trim() || $isSubmitting) return;
        if ($selectedCategoryId === 'new' && !newCategoryName.trim()) {
            $error = "Please enter a name for the new category.";
            return;
        }
         if ($selectedCategoryId === '') {
            $error = "Please select a category.";
            return;
        }

		$isSubmitting = true;
		$error = null;
        let categoryIdToUse: number;

		try {
            // 1. Handle category creation if needed
			if ($selectedCategoryId === 'new') {
                const newCategory = await onAddCategory(newCategoryName.trim());
                categoryIdToUse = newCategory.id;
			} else {
                categoryIdToUse = Number($selectedCategoryId);
            }

            // 2. Create the item payload
			const payload: ItemPayload = {
				name: itemName.trim(),
				category_id: categoryIdToUse,
				note: itemNote.trim() || null, // Send null if empty
                price_match: $priceMatch,
			};

            // 3. Call parent's add item handler
			await onAddItem(payload);

			// 4. Reset form on success
			itemName = '';
			itemNote = '';
            newCategoryName = '';
            $priceMatch = false;
            // Reset selected category *carefully* - maybe back to default?
            if (categories.length > 0) {
                $selectedCategoryId = categories[0].id;
            } else {
                 $selectedCategoryId = ''; // Or 'new' if no categories exist?
            }

		} catch (err: any) {
			console.error("Failed to add item:", err);
			$error = err.message || "An error occurred while adding the item.";
		} finally {
			$isSubmitting = false;
		}
	}
</script>

<form on:submit|preventDefault={handleSubmit} class="space-y-4 p-4 bg-gray-50 dark:bg-gray-800 rounded-lg shadow mb-6">
    <h3 class="text-lg font-medium text-gray-900 dark:text-white">Add New Item</h3>
	<div>
		<label for="item-name" class="block text-sm font-medium text-gray-700 dark:text-gray-300">Item Name*</label>
		<input
			type="text"
			id="item-name"
			bind:value={itemName}
			required
			class="mt-1 block w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm text-gray-900 dark:text-white"
		/>
	</div>

	<div>
		<label for="category-select" class="block text-sm font-medium text-gray-700 dark:text-gray-300">Category*</label>
		<select
			id="category-select"
			bind:value={selectedCategoryId}
            required
			class="mt-1 block w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm text-gray-900 dark:text-white"
		>
            <option value="" disabled>-- Select Category --</option>
			{#each categories as category (category.id)}
				<option value={category.id}>{category.name}</option>
			{/each}
			<option value="new">-- Create New Category --</option>
		</select>
	</div>

	{#if $selectedCategoryId === 'new'}
		<div>
			<label for="new-category-name" class="block text-sm font-medium text-gray-700 dark:text-gray-300">New Category Name*</label>
			<input
				type="text"
				id="new-category-name"
                placeholder="e.g., Pantry"
				bind:value={newCategoryName}
				required
				class="mt-1 block w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm text-gray-900 dark:text-white"
			/>
		</div>
	{/if}

	<div>
		<label for="item-note" class="block text-sm font-medium text-gray-700 dark:text-gray-300">Note (Optional)</label>
		<input
			type="text"
			id="item-note"
			bind:value={itemNote}
            placeholder="e.g., Brand name, quantity"
			class="mt-1 block w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm text-gray-900 dark:text-white"
		/>
	</div>

    <div class="flex items-center">
        <input
            id="price-match"
            type="checkbox"
            bind:checked={priceMatch}
            class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 dark:border-gray-600 rounded dark:bg-gray-700 dark:focus:ring-offset-gray-800"
        />
        <label for="price-match" class="ml-2 block text-sm text-gray-900 dark:text-gray-300">
            Flag for Price Match
        </label>
    </div>


	{#if $error}
		<p class="text-sm text-red-600 dark:text-red-400">{$error}</p>
	{/if}

	<button
		type="submit"
		disabled={$isSubmitting || !itemName.trim() || ($selectedCategoryId === 'new' && !newCategoryName.trim()) || $selectedCategoryId === ''}
		class="w-full inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
	>
		{#if $isSubmitting}
            Adding...
        {:else}
            Add Item
        {/if}
	</button>
</form>

// frontend/src/components/AddItemForm.jsx
// src/components/AddItemForm.jsx
import React, { useState, useEffect } from 'react';

function AddItemForm({ categories = [], onAddItem, onAddCategory }) {
    const [itemName, setItemName] = useState('');
    const [itemNote, setItemNote] = useState('');
    const [selectedCategoryId, setSelectedCategoryId] = useState('');
    const [newCategoryName, setNewCategoryName] = useState('');
    const [priceMatch, setPriceMatch] = useState(false);
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [error, setError] = useState(null);

    // Effect to set default category when categories load or change
    useEffect(() => {
        if (categories.length > 0 && selectedCategoryId === '') {
            setSelectedCategoryId(categories[0].id.toString()); // Ensure string for select value
        }
        // If no categories exist and user hasn't chosen 'new', maybe default to 'new'?
        // else if (categories.length === 0 && selectedCategoryId === '') {
        //    setSelectedCategoryId('new');
        // }
    }, [categories, selectedCategoryId]); // Re-run if categories change or selection is reset


    const handleSubmit = async (e) => {
        e.preventDefault(); // Prevent default form submission
        if (!itemName.trim() || isSubmitting) return;
        if (selectedCategoryId === 'new' && !newCategoryName.trim()) {
            setError("Please enter a name for the new category.");
            return;
        }
        if (selectedCategoryId === '') {
            setError("Please select a category or create a new one.");
            return;
        }

        setIsSubmitting(true);
        setError(null);
        let categoryIdToUse;

        try {
            // 1. Handle category creation if needed
            if (selectedCategoryId === 'new') {
                // Call parent's add category handler which returns the new category
                const newCategory = await onAddCategory(newCategoryName.trim());
                categoryIdToUse = newCategory.id;
                // Optional: Automatically select the newly created category in the dropdown?
                // setSelectedCategoryId(newCategory.id.toString()); // Needs categories to update first
            } else {
                categoryIdToUse = Number(selectedCategoryId);
            }

            // 2. Create the item payload
            const payload = {
                name: itemName.trim(),
                category_id: categoryIdToUse,
                note: itemNote.trim() || null, // Send null if empty
                price_match: priceMatch,
            };

            // 3. Call parent's add item handler
            await onAddItem(payload);

            // 4. Reset form on success
            setItemName('');
            setItemNote('');
            setNewCategoryName('');
            setPriceMatch(false);
            setError(null);
            // Reset selected category back to the first available or empty
            setSelectedCategoryId(categories.length > 0 ? categories[0].id.toString() : '');

        } catch (err) {
            console.error("Failed to add item or category:", err);
            setError(err.message || "An error occurred.");
            // Don't reset form on error so user can fix input
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <form onSubmit={handleSubmit} className="card bg-base-100 shadow mb-6 shrink-0">
          <div className="card-body space-y-4 p-4 md:p-6">
            <h3 className="text-lg font-medium card-title">Add New Item</h3>
            {error && (
                <div className="alert alert-error text-sm p-2">
                    <svg xmlns="http://www.w3.org/2000/svg" className="stroke-current shrink-0 h-5 w-5" fill="none" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                    <span>{error}</span>
                </div>
            )}
            <div className="form-control">
                <label htmlFor="item-name" className="label">
                    <span className="label-text">Item Name*</span>
                </label>
                <input
                    type="text"
                    id="item-name"
                    value={itemName}
                    onChange={(e) => setItemName(e.target.value)}
                    required
                    className="input input-bordered w-full"
                />
            </div>

            <div className="form-control">
                <label htmlFor="category-select" className="label">
                     <span className="label-text">Category*</span>
                </label>
                <select
                    id="category-select"
                    value={selectedCategoryId}
                    onChange={(e) => {
                        setSelectedCategoryId(e.target.value);
                        if (e.target.value !== 'new') setNewCategoryName(''); // Clear new name if existing selected
                        setError(null); // Clear category errors on change
                    }}
                    required
                    className="select select-bordered w-full"
                >
                    <option value="" disabled>-- Select Category --</option>
                    {categories.map(category => (
                        <option key={category.id} value={category.id.toString()}>
                            {category.name}
                        </option>
                    ))}
                    <option value="new">-- Create New Category --</option>
                </select>
            </div>

            {selectedCategoryId === 'new' && (
                <div className="form-control">
                    <label htmlFor="new-category-name" className="label">
                        <span className="label-text">New Category Name*</span>
                    </label>
                    <input
                        type="text"
                        id="new-category-name"
                        placeholder="e.g., Pantry"
                        value={newCategoryName}
                        onChange={(e) => {
                            setNewCategoryName(e.target.value);
                             if (e.target.value.trim()) setError(null); // Clear error if user types
                        }}
                        required
                        className="input input-bordered w-full"
                    />
                </div>
            )}

            <div className="form-control">
                 <label htmlFor="item-note" className="label">
                     <span className="label-text">Note (Optional)</span>
                 </label>
                <input
                    type="text"
                    id="item-note"
                    value={itemNote}
                    onChange={(e) => setItemNote(e.target.value)}
                    placeholder="e.g., Brand name, quantity"
                    className="input input-bordered w-full"
                />
            </div>

            <div className="form-control">
                <label className="label cursor-pointer justify-start gap-4">
                     <input
                        id="price-match"
                        type="checkbox"
                        checked={priceMatch}
                        onChange={(e) => setPriceMatch(e.target.checked)}
                        className="checkbox checkbox-primary"
                    />
                    <span className="label-text">Flag for Price Match</span>
                </label>
            </div>

            <div className="card-actions justify-end">
                 <button
                    type="submit"
                    disabled={isSubmitting || !itemName.trim() || selectedCategoryId === '' || (selectedCategoryId === 'new' && !newCategoryName.trim())}
                    className="btn btn-primary w-full md:w-auto"
                >
                    {isSubmitting ? <> <span className="loading loading-spinner loading-xs"></span> Adding... </> : 'Add Item'}
                </button>
            </div>
           </div>
        </form>
    );
}

export default AddItemForm;
